services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: travel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - travel-net
        depends_on:
            - db
            - redis

    webserver:
        image: nginx:latest
        container_name: travel-webserver
        restart: unless-stopped
        ports:
            - '80:80'
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - travel-net
        depends_on:
            -   app

    db:
        image: mysql:8.0
        container_name: travel-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - travel-net

    redis:
        image: redis:alpine
        container_name: travel-redis
        restart: unless-stopped
        ports:
            - '6379:6379'
        networks:
            - travel-net

    queue:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: travel-queue
        restart: unless-stopped
        working_dir: /var/www
        command: php artisan horizon
        volumes:
            -   ./:/var/www
        networks:
            - travel-net
        depends_on:
            - app
            - redis

networks:
    travel-net:
        driver: bridge

volumes:
    dbdata:
